command:
  - gunicorn
  - app:app
  - -c
  - gunicorn_config.py

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: USE_MOCK_BACKEND
    value: "false"
  - name: GENIE_SPACE_ID
    valueFrom: genie-space
  - name: NEO4J_URI
    valueFrom: neo4j-uri
  - name: NEO4J_USERNAME
    valueFrom: neo4j-username
  - name: NEO4J_PASSWORD
    valueFrom: neo4j-password
