command:
  - streamlit
  - run
  - app.py

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: CATALOG
    value: graph-enriched-lakehouse
  - name: SCHEMA
    value: graph-enriched-schema
  - name: MCP_SCHEMA_CONNECTION_NAME
    value: neo4j_agentcore_mcp
  - name: MCP_SCHEMA_PATH
    value: /
  - name: MCP_SCHEMA_TOOL_NAME
    value: neo4j-mcp-server-target___get-schema
  - name: MCP_SCHEMA_TOOL_ARGUMENTS
    value: properties
